services:
  algorithm-exercises-go:
    image: algorithm-exercises-go:latest
    build:
      context: .
      target: testing
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO} ## (1) ## INFO | WARN | ERROR | DEBUG
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## TRUE | FALSE
    volumes:
      - ./coverage:/app/coverage
    profiles: ["testing"]

  algorithm-exercises-go-lint:
    image: algorithm-exercises-go:lint
    build:
      context: .
      target: lint
    # environment:
      # LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      # BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./:/app
    profiles: ["lint"]

  algorithm-exercises-go-dev:
    image: algorithm-exercises-go:dev
    build:
      context: .
      target: development
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO} ## (1) ## INFO | WARN | ERROR | DEBUG
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## TRUE | FALSE
    volumes:
      - ./:/app
    profiles: ["development", "lint"]
