/**
 * Even Fibonacci numbers
 *
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

package projecteuler

import (
	"testing"
)

func TestProblem0002(t *testing.T) {

	solutionFound := 4613732
	top := 4000000

	ans := Problem0002(top)

	if ans != solutionFound {
		t.Errorf("Problem0002(%d) = %d; want %d", top, ans, solutionFound)
	}
}
