---
name: Go CI Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

env:
  LOG_LEVEL: WARN

jobs:
  lint:
    name: "Go CI LINT"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022", "ubuntu-24.04", "macos-14"]
        go: ["1.24.x", "1.25.x", "1.26.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: false

      - run: go version

      - name: Test Styling (gofmt & modernize)
        run: make test/styling

      - name: Lint (go vet)
        run: go vet -v ./...

      # yamllint disable rule:line-length
      - name: Lint golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          args: --timeout=10m
          version: v2.12.2
          skip-cache: true
          # yamllint enable rule:line-length
