---
name: Go CI Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

env:
  LOG_LEVEL: WARN

jobs:
  lint:
    name: "Go CI LINT"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022", "ubuntu-24.04", "macos-14"]
        go: ["1.24.x", "1.25.x", "1.26.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: false

      - run: go version

      - name: Test Styling (gofmt & modernize)
        run: make test/styling

      - name: Lint (go vet)
        run: go vet -v ./...

      # yamllint disable rule:line-length
      - name: Lint golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          args: --timeout=10m
          version: v2.12.2
          skip-cache: true
          # yamllint enable rule:line-length
