name: Go

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

env:
  LOG_LEVEL: WARN

jobs:

  build:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: [
          # "windows-latest",
          "ubuntu-latest",
          "macOS-latest"
        ]
        go: ["1.18.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: "go test ./..."

    - name: Lint
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1.1"
        install-go: false
        cache-key: ${{ matrix.go }}

    - name: Test
      run: go test -v -coverprofile=coverage.out ./...

    - name: Coverage
      run: go tool cover -func=coverage.out

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
