---
name: Markdown Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule
        # at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install -g --ignore-scripts markdownlint-cli@v0.49.1

      - name: Check tools
        run: markdownlint --version

      - name: Lint
        run: >
          markdownlint '**/*.md' --ignore node_modules
          && echo '✔  Your code looks good.'
